// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9qOu4U6PsjLi71bfacyswg-W_X634lZA',
    appId: '1:788822507571:web:3be5431492670cbaf36346',
    messagingSenderId: '788822507571',
    projectId: 'aprovapost',
    authDomain: 'aprovapost.firebaseapp.com',
    databaseURL: 'https://aprovapost-default-rtdb.firebaseio.com',
    storageBucket: 'aprovapost.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbcEsTl2VuLFkRLTy2tq2XjoHm6M5R6Xo',
    appId: '1:788822507571:android:e75bfbb658e53be1f36346',
    messagingSenderId: '788822507571',
    projectId: 'aprovapost',
    databaseURL: 'https://aprovapost-default-rtdb.firebaseio.com',
    storageBucket: 'aprovapost.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwc6AqfqzfErKQqAJKlik_Ks--D948crM',
    appId: '1:788822507571:ios:e75f28f777e3e563f36346',
    messagingSenderId: '788822507571',
    projectId: 'aprovapost',
    databaseURL: 'https://aprovapost-default-rtdb.firebaseio.com',
    storageBucket: 'aprovapost.appspot.com',
    iosClientId: '788822507571-7bp6vfor28bs4o540a8f24u4vi1vl30a.apps.googleusercontent.com',
    iosBundleId: 'com.splneto.aprova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwc6AqfqzfErKQqAJKlik_Ks--D948crM',
    appId: '1:788822507571:ios:e75f28f777e3e563f36346',
    messagingSenderId: '788822507571',
    projectId: 'aprovapost',
    databaseURL: 'https://aprovapost-default-rtdb.firebaseio.com',
    storageBucket: 'aprovapost.appspot.com',
    iosClientId: '788822507571-7bp6vfor28bs4o540a8f24u4vi1vl30a.apps.googleusercontent.com',
    iosBundleId: 'com.splneto.aprova',
  );
}
